export default [
  "Christmas Island",
  "Eritrea",
  "Samoa",
  "North Macedonia",
  "Djibouti",
  "Jordan",
  "Pakistan",
  "French Polynesia",
  "Ireland",
  "Mauritania",
  "Denmark",
  "Namibia",
  "Ghana",
  "South Sudan",
  "Slovakia",
  "American Samoa",
  "Moldova",
  "North Korea",
  "Macau",
  "Turks and Caicos Islands",
  "Seychelles",
  "Armenia",
  "Curaçao",
  "Guadeloupe",
  "British Indian Ocean Territory",
  "Equatorial Guinea",
  "Syria",
  "Angola",
  "Tajikistan",
  "Venezuela",
  "United States Minor Outlying Islands",
  "Åland Islands",
  "Poland",
  "Saudi Arabia",
  "Republic of the Congo",
  "Bosnia and Herzegovina",
  "United States Virgin Islands",
  "New Caledonia",
  "San Marino",
  "Czechia",
  "Guatemala",
  "South Korea",
  "Estonia",
  "Nepal",
  "Kosovo",
  "Botswana",
  "Philippines",
  "Saint Pierre and Miquelon",
  "Iraq",
  "Lebanon",
  "Burundi",
  "Mongolia",
  "Faroe Islands",
  "Paraguay",
  "Svalbard and Jan Mayen",
  "Tokelau",
  "Guernsey",
  "Caribbean Netherlands",
  "Algeria",
  "France",
  "Netherlands",
  "Greenland",
  "Sint Maarten",
  "Chad",
  "Finland",
  "Panama",
  "Palestine",
  "Yemen",
  "Brazil",
  "Nigeria",
  "Palau",
  "Japan",
  "Tanzania",
  "Kazakhstan",
  "Portugal",
  "South Georgia",
  "Sri Lanka",
  "Germany",
  "Western Sahara",
  "Myanmar",
  "Colombia",
  "Peru",
  "Senegal",
  "Kyrgyzstan",
  "China",
  "Afghanistan",
  "Turkey",
  "Liberia",
  "South Africa",
  "Chile",
  "Malta",
  "Kiribati",
  "Cape Verde",
  "Jersey",
  "Iceland",
  "Gambia",
  "Vanuatu",
  "Uruguay",
  "Oman",
  "Sudan",
  "India",
  "Laos",
  "Aruba",
  "Martinique",
  "Comoros",
  "Spain",
  "Antigua and Barbuda",
  "Uzbekistan",
  "Maldives",
  "Gibraltar",
  "Indonesia",
  "Pitcairn Islands",
  "Vietnam",
  "Malaysia",
  "Cook Islands",
  "Eswatini",
  "Uganda",
  "Madagascar",
  "Fiji",
  "Norway",
  "Antarctica",
  "Bouvet Island",
  "Cyprus",
  "Taiwan",
  "Papua New Guinea",
  "Rwanda",
  "DR Congo",
  "Cameroon",
  "Serbia",
  "Lithuania",
  "French Southern and Antarctic Lands",
  "Cambodia",
  "Saint Helena, Ascension and Tristan da Cunha",
  "United Arab Emirates",
  "Bermuda",
  "Monaco",
  "Cuba",
  "Hong Kong",
  "Northern Mariana Islands",
  "Togo",
  "Luxembourg",
  "Mauritius",
  "Argentina",
  "Grenada",
  "Nicaragua",
  "Niue",
  "Ukraine",
  "Guyana",
  "Niger",
  "Benin",
  "Saint Lucia",
  "Tuvalu",
  "Norfolk Island",
  "Egypt",
  "Saint Kitts and Nevis",
  "Lesotho",
  "Tonga",
  "Georgia",
  "Ethiopia",
  "Dominican Republic",
  "Saint Vincent and the Grenadines",
  "Belize",
  "Isle of Man",
  "Morocco",
  "Haiti",
  "Mayotte",
  "Burkina Faso",
  "Bangladesh",
  "Kuwait",
  "Réunion",
  "Jamaica",
  "Romania",
  "São Tomé and Príncipe",
  "Bahamas",
  "Mexico",
  "Saint Martin",
  "El Salvador",
  "Saint Barthélemy",
  "Micronesia",
  "Turkmenistan",
  "Anguilla",
  "Central African Republic",
  "Suriname",
  "Belgium",
  "Sweden",
  "Bolivia",
  "Montenegro",
  "Mozambique",
  "Latvia",
  "Malawi",
  "Mali",
  "Vatican City",
  "Montserrat",
  "Austria",
  "Albania",
  "British Virgin Islands",
  "Zambia",
  "French Guiana",
  "Liechtenstein",
  "Qatar",
  "Solomon Islands",
  "Nauru",
  "Greece",
  "Libya",
  "Guinea-Bissau",
  "Barbados",
  "Honduras",
  "Somalia",
  "Cayman Islands",
  "Italy",
  "Wallis and Futuna",
  "Andorra",
  "Ecuador",
  "Kenya",
  "Bahrain",
  "United Kingdom",
  "Guinea",
  "Heard Island and McDonald Islands",
  "Russia",
  "Brunei",
  "Zimbabwe",
  "Guam",
  "Australia",
  "Slovenia",
  "Belarus",
  "Thailand",
  "New Zealand",
  "Tunisia",
  "Marshall Islands",
  "Sierra Leone",
  "Bhutan",
  "United States",
  "Switzerland",
  "Falkland Islands",
  "Cocos (Keeling) Islands",
  "Gabon",
  "Dominica",
  "Canada",
  "Trinidad and Tobago",
  "Puerto Rico",
  "Singapore",
  "Hungary",
  "Costa Rica",
  "Israel",
  "Bulgaria",
  "Azerbaijan",
  "Timor-Leste",
  "Iran",
  "Croatia",
  "Ivory Coast",
];
