export const ArabCountries = [
  "Saudi Arabia",
  "UAE",
  "Bahrain",
  "Kuwait",
  "Oman",
  "Qatar",
  "Algeria",
  "Comoros",
  "Djibouti",
  "Egypt",
  "Iraq",
  "Jordan",
  "Lebanon",
  "Libya",
  "Mauritania",
  "Morocco",
  "Palestine",
  "Somalia",
  "Sudan",
  "Syria",
  "Tunisia",
  "United Arab Emirates",
  "Yemen"
]