export default [
  "Intramuscular",
  "Nasal",
  "Topical",
  "Intraosasseous",
  "Intrathecal",
  "Intraperitoneal",
  "Intradermal",
  "Nasogastric",
  "Sub Lingual",
  "Per Rectum",
  "Sub Cutaneous",
  "Per Vaginal",
  "Oral",
  "Inhalation",
];
