export default {
  "home": [
    "ROLE_Delete-Agency",
      "ROLE_Read-Agency",
      "ROLE_Create-Agency",
      "ROLE_Read-Agencies",
      "ROLE_Update-Agency",
      "ROLE_Approve-Bought-Insurances-Agency",
      "ROLE_Read-Bought-Insurances",
      "ROLE_Update-Bought-Insurance",
      "ROLE_Review-Bought-Insurance",
      "ROLE_Delete-Bought-Insurance",
      "ROLE_Create-Bought-Insurance",
      "ROLE_Create-Insurance",
      "ROLE_Read-Insurances",
      "ROLE_Read-Insurance",
      "ROLE_Update-Insurance",
      "ROLE_Delete-Insurance",
      "ROLE_Read-Packages",
      "ROLE_Update-Package",
      "ROLE_Create-Package",
      "ROLE_Delete-Package",
      "ROLE_Read-Package",
      "ROLE_Read-Services",
      "ROLE_Update-Service",
      "ROLE_Delete-Service",
      "ROLE_Read-Service",
      "ROLE_Create-Service",
      "ROLE_Delete-Privilege",
      "ROLE_Read-Roles",
      "ROLE_Update-User",
      "ROLE_Read-Privilege",
      "ROLE_Update-Role",
      "ROLE_Read-Privileges",
      "ROLE_Delete-User",
      "ROLE_Read-Role",
      "ROLE_Create-User",
      "ROLE_Delete-Role",
      "ROLE_Read-User",
      "ROLE_Create-Role",
      "ROLE_Create-Privilege",
      "ROLE_Update-Privilege",
  ],
  "user_management": [""], 
  "role_management": [""],
  "privileges": [""]
}